### ISSUE TITLE
Stuck on "changing site domain"

### ISSUE THREAD

**Issue by CarlosSouza** [artifex404/local-bedrock#2]
I'm trying to import the local-bedrock.zip file as described in the Readme, but it get's stuck with the message "Changing site domain..." (I'm trying to use the .local TLD).

Also, I've already tried using both Nginx and Apache.
![screen shot 2018-09-24 at 07 22 54](https://user-images.githubusercontent.com/833638/45947462-b83b6780-bfca-11e8-8cf5-6fe33a200424.png)

**Comment by artifex404** [comment]
You can try to hit Help -> Restart Local Machine in the Local application. That might help.

However I think Flywheel guys changed the structure of Nginx server config files, so I have to update my repository.

Custom environment is currently at version 1.3.1 and is changing fast, so I'll wait a bit for it to settle down and update the repository.

I'll try to keep up-to-date with the latest Local and Custom Local Environment versions, so make sure to update to the latest ones.

**Comment by artifex404** [comment]
This has been now fixed with the latest commit and updated instructions.

**Comment by CarlosSouza** [comment]
Hi @artifex404 ,

Thanks for your support. I'm using Local v2.4.3 and macOS 10.14, but the problem persists (for both Apache and nginx).

**Comment by artifex404** [comment]
I did release the fix for nginx for now. Note the additional final steps in the installation instructions. It didn't work? @CarlosSouza

**Comment by CarlosSouza** [comment]
I stopped at step 5, since it gets stuck on "changing site domain" and never finishes the process.
Is it supposed to work even if the site creation has not been finished yet?

**Comment by artifex404** [comment]
No, it shouldn't stop. I'll test again. With the changes I made it did not get stuck for me anymore.

**Comment by artifex404** [comment]
One thing to keep in mind, do not use **.local** domain, especially on mac. As the Bonjour service grabs all **.local** domains, and that might be the reason your installation gets stuck. Use a **.test** domain for local development, as it's a standard for development and won't be used as a global TLD. See https://en.wikipedia.org/wiki/.test @CarlosSouza

**Comment by CarlosSouza** [comment]
@artifex404 Thanks a lot, this is exactly the issue (using .local domain). It's working now :)

**Comment by CarlosSouza** [comment]
By the way, it could be useful to edit site's path inside the wp-clip.yml file:
https://local.getflywheel.com/community/t/how-to-install-bedrock-with-local-by-flywheel/2376/10
